import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Mainbodycontainer, Mypiccontainer, Myemailcontainer, Aboutcontainer } from '../styles/Homestyles'
import Image from 'next/image'
import mypic from '../icons/mypic.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Mainbodycontainer>
        <Mypiccontainer>
          <Image src={mypic} alt="pic" height={400} width={300}/>
        </Mypiccontainer>
        <Myemailcontainer>
          <span >Matyila2sango@gmail.com</span>
        </Myemailcontainer>
        <Aboutcontainer>
          <h4>About me 😊 --------------------</h4>
          <p>
            My name is Sango Matyila. I am a computer science graduate from university of the western cape.
            I have a passion for programming. I like to code whether it be creating applications or websites.
            <br/><br/>
            My interest in the computing industry started long time ago before I even possesed an electronic device.
            I was always interested about how these devices that people uses work and how are they enables them to do what they want
             just with the strokes of their finders. So, when I grew up I told myself thats what want to do, create applications
             that will benefit the lives of everyone in a good way.
            <br/><br/>
            To be a developer at SovTec would be a dream come true. Working with world-class expert team of developers would be a 
            greate opportunity for me to learn new skills and to learn from my senior how this industry works and how to create beautiful, functional software.
            <br/><br/>
            
          </p>
        </Aboutcontainer>

      </Mainbodycontainer>

      
    </div>
  )
}
