import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Mainbodycontainer, Myemailcontainer } from '../styles/Toolsstyels'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Mainbodycontainer>
        <Myemailcontainer>
          <span >Matyila2sango@gmail.com</span>
        </Myemailcontainer>
        
      </Mainbodycontainer>
      
    </div>
  )
}